### ISSUE TITLE
Why are some incidents not shown?

### ISSUE THREAD

**Issue by daveloyall** [hiddentao/ois-incidents-map#1]
If I adjust the parameters just right, I can see this message:

```
2 incidents (1 shown)
```

Why is one incident not shown?

**Comment by hiddentao** [comment]
We don't have lat-lng co-ordinates for some incidents. I should probably change that to 'unmappable' or something or just remove it altogether.

**Comment by hiddentao** [comment]
Now fixed.

**Comment by daveloyall** [comment]
This was changed in commit 28720d608929ce0873e1ce9667d8de36c50720a6.

Wow, removing some incidents is really not the correct answer.  Each incident represents a OIS, after all...

Each unmappable incident does include other data that could be displayed, correct?  Age, perhaps a narrative.. 

Could you make a list of the unmappables and throw it on the side of the page?
