### ISSUE TITLE
something is broken

### ISSUE THREAD

**Issue by danhammer** [hiddentao/ois-incidents-map#2]
I can't identify what recent push broke the [front end](hiddentao.github.io/ois-incidents-map/).  Any chance on rolling it back to have it accessible for today's Police Data Initiative meeting -- just in case someone is interested.

**Comment by hiddentao** [comment]
Apologies, I'd accidentally overwritten the repo with contents from another project.

**Comment by danhammer** [comment]
not to worry at all! I just want to make sure that your work is showcased at every possible opportunity.  thanks!
